# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProyectoFreeTimeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase'
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'

  # Pods for ProyectoFreeTimeApp

  target 'ProyectoFreeTimeAppUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase'
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
  end

end
